Fix replication issues
PastVu/pastvu pull request #321
Opened 2020-12-05 22:29 UTC by aeifn

Probably fixes https://github.com/PastVu/pastvu/issues/319

Нужно будет держать отдельный глобально запущенный мастер.

2020-12-05 23:08 UTC, kabalin commented on config/local.config.js.docker-example
> +        master: process.env.MASTER === 'true',
Если в `docker-compose.yml` переменные окружения не заданы, то у разработчика, который следуя инструкции скопирует этот файл, `notifier` и `master` будут `false`. Мне кажется нужно в `default.config.js` по умолчанию их ставить в true.

2020-12-05 23:15 UTC, aeifn commented on config/local.config.js.docker-example
> +        master: process.env.MASTER === 'true',
Тут главное, чтобы в продакшн не уехало нечаянно с true. А то начнется массовая рассылка )
docker-example поправил, довод про разработчика правильный: https://github.com/PastVu/pastvu/pull/321/commits/2e16b84fbd5452a14c0065e5b352c0b177bed003

2020-12-07 02:11 UTC, klimashkin commented
Let's switch to primary/replica terminology

2020-12-07 02:12 UTC, klimashkin requested changes
Let's switch to primary/replica terminology

2020-12-07 09:17 UTC, klimashkin approved these changes

2020-12-07 10:19 UTC, merged