Parse coord
PastVu/pastvu pull request #558
Opened 2023-01-24 13:35 UTC by yuriy-zhilovets2

Возможно, файл geo-coord-parser при деплое стоит минифицировать

2023-01-24 20:13 UTC, yuriy-zhilovets2 commented
Я немного переделал внутренности библиотеки, добавив дополнительные шаблоны. Раз это потребовало изменений, то заодно и выкинул пару ненужных функций, чтобы сократить количество загружаемого кода. И добавил define, поскольку оригинал работал через модули Node (module.export).
В принципе можно оставить оригинальную библиотеку, вынеся изменения в дополнительную обертку, тогда можно будет ее обновлять. Нужно ли это или предпочтительней зафиксироваться на одной версии и выиграть в размере кода? Если да, то что делать с module.export ?

2023-01-26 10:59 UTC, mkgrgis commented
> Еще соберите все изменения в один коммит.

Как это делать? git refactor или что-то упустил? Иногда надо объединить, а не нахожу документации.

2023-01-26 11:08 UTC, kabalin commented
> Как это делать? git refactor или что-то упустил? Иногда надо объединить, а не нахожу документации.

Есть [несколько способов](https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together), я привык использовать `git rebase -i <commit ref>`.

2023-01-26 14:38 UTC, kabalin commented
@yuriy-zhilovets2 

> Я немного переделал внутренности библиотеки, добавив дополнительные шаблоны. Раз это потребовало изменений, то заодно и выкинул пару ненужных функций, чтобы сократить количество загружаемого кода. И добавил define, поскольку оригинал работал через модули Node (module.export). В принципе можно оставить оригинальную библиотеку, вынеся изменения в дополнительную обертку, тогда можно будет ее обновлять. Нужно ли это или предпочтительней зафиксироваться на одной версии и выиграть в размере кода? Если да, то что делать с module.export ?

Давайте оригинал. Это UMD https://github.com/ianengelbrecht/geo-coordinates-parser/blob/master/bundle/geocoordsparser.js должно работать без оборачивания, просто скопируйте без изменений в `lib` и используйте в `Utils.js` так как вы сейчас с `geo-coord-parser` делаете. Обратите внимание, что вызов `convert` возвращает объект (в текущем виде `parseCoordinates` работать не будет).

И все в один коммит пожалуйста, в теле коммита упомяните источник библиотеки и лицензию.

2023-01-26 14:43 UTC, kabalin commented on public/js/lib/Utils.js
> +                    const coord = geoParser(s, 7);
Мы используем точность до 6 знаков.

2023-01-26 15:17 UTC, yuriy-zhilovets2 commented
После сборки в один коммит через git rebase Гит сообщает, что удаленная ветка опережает и после git pull возвращает все коммиты назад. Я что-то неправильно делаю?

2023-01-26 15:45 UTC, kabalin commented
> После сборки в один коммит через git rebase Гит сообщает, что удаленная ветка опережает и после git pull возвращает все коммиты назад. Я что-то неправильно делаю?

после сквоша в один коммит `git pull` не нужен, он все притянет назад, нужен force push (`git push -f HEAD`) принудительно переписать ветку в репозитарии.

2023-01-26 19:49 UTC, kabalin commented on public/js/lib/Utils.js
> +            const sec_pat = /SEC(ONDS)?|SECONDO|SEGONDO|С(ЕК)?(УНД)?/ig;
Все эти переменные можно внутрь функции перенести, вообще говоря я сомневаюсь что нужен такой спектр вариантов, оставьте только направления на русском.

2023-01-27 07:02 UTC, mkgrgis commented on public/js/lib/Utils.js
> +            const sec_pat = /SEC(ONDS)?|SECONDO|SEGONDO|С(ЕК)?(УНД)?/ig;
Не напишу о датском и итальянском варианте, а вот немецкий и французский используются регулярно. Если на то пошло, то здесь нет реально использовавшихся недавно в нескольких источниках болгарских и украинских слов. Так что проблема не столько в сужении, сколько в расширении списка. Языки аудитории PastVu это *совсем не то* что языки указаний на координаты, которые пользователи могут копировать из источников, если уж мы вводим функцию распознания бувально всего что могут назвать географическими координатами.

2023-01-27 07:58 UTC, yuriy-zhilovets2 commented
Если перенести РВ в функцию, они будут создаваться при каждом вызове функции. Это лишнее время, пусть и не большое, но из мелких задержек складываются большие.

2023-01-27 12:39 UTC, kabalin commented
> Если перенести РВ в функцию, они будут создаваться при каждом вызове функции. Это лишнее время, пусть и не большое, но из мелких задержек складываются большие. И если мелких задержек можно избежать, то почему это не сделать?

Хорошо, что вы принимаете во внимание время выполнения, но в данном случае можно пренебречь. У вас эта "мелкая задержка" возникает только при вводе координат в поле, и потом парсинг текста с заменой не настолько ресурсоемкая задача. Имелся бы смысл выносить если бы они использовались вне функции.

2023-01-27 12:42 UTC, kabalin commented
> > После сборки в один коммит через git rebase Гит сообщает, что удаленная ветка опережает и после git pull возвращает все коммиты назад. Я что-то неправильно делаю?
> 
> после сквоша в один коммит `git pull` не нужен, он все притянет назад, нужен force push (`git push -f HEAD`) принудительно переписать ветку в репозитарии.

Учитывая количество коммитов и мержей, здесь уже лучше сделать `git reset` до последнего коммита из мастера и сделать повторный коммит изменений, затем force push.

2023-01-27 14:45 UTC, kabalin commented on public/js/lib/Utils.js
> +            const sec_pat = /SEC(ONDS)?|SECONDO|SEGONDO|С(ЕК)?(УНД)?/ig;
@mkgrgis пошлите PR в https://github.com/ianengelbrecht/geo-coordinates-parser по возможности, если примут, здесь можно будет обновить библиотеку и убрать все эти переменные. Отдельное замечание: шаблон `n_pat` отличается от других (зачем-то добавлен "lookbehind")?

2023-01-27 14:49 UTC, yuriy-zhilovets2 commented on public/js/lib/Utils.js
> +            const sec_pat = /SEC(ONDS)?|SECONDO|SEGONDO|С(ЕК)?(УНД)?/ig;
Из-за неоднозначности. Буква "С" может означать и секунды,  и север. У автора есть такая же неоднозначность с буквами s и S, но он решает ее введением отдельного РВ.

2023-01-27 15:53 UTC, mkgrgis commented on public/js/lib/Utils.js
> +            const sec_pat = /SEC(ONDS)?|SECONDO|SEGONDO|С(ЕК)?(УНД)?/ig;
> @mkgrgis пошлите PR в https://github.com/ianengelbrecht/geo-coordinates-parser по возможности - если примут, здесь можно будет обновить библиотеку и убрать все эти переменные.

Попробую. Там вроде как южноафриканские биологи, едва ли им инетресны европейские языки.

2023-01-28 10:34 UTC, kabalin commented
@yuriy-zhilovets2 вы кажется когда rebase и pull делали задели коммиты которые в мастере были, сейчас сильно искажена история, давайте я исправлю и обновлю эту ветку.

![image](https://user-images.githubusercontent.com/329780/215261819-1d607665-ad1f-453c-b290-3083343ea738.png)

2023-01-28 10:43 UTC, yuriy-zhilovets2 commented
Вполне возможно. В Гите очень легко все сломать. Какие сейчас мои действия? Может быть, уничтожить эту ветку и этот пулл и сделать все заново?
Второй вопрос: что делать с оригинальным файлом geocoordsparser, который сейчас не проходит тест?

2023-01-28 11:01 UTC, kabalin commented
Исправлено. Для информации, я сделал reset до вашего первого коммита затем все изменения в ветке добавил в этот первый коммит, затем сделал rebase к мастеру чтобы применить коммит на чистый мастер.
```
2753 pastvu:parse_coord> git reset 0a6842bafd17ab10ba036866771c3b8e84882332
Unstaged changes after reset:
M       public/js/lib/Utils.js
D       public/js/lib/geo-coord-parser.js
M       views/mail/notice.pug
2754 pastvu:parse_coord> git add .
2755 pastvu:parse_coord> git commit -a --amend
[parse_coord 6df67bad] Add parsing of geo coordinates in various formats
 Author: Yuriy Zhilovets <yz@test>
 Date: Thu Jan 26 17:15:25 2023 +0300
 4 files changed, 37 insertions(+), 14 deletions(-)
 create mode 100644 public/js/lib/geocoordsparser.js
2756 pastvu:parse_coord> git fetch origin 
2757 pastvu:parse_coord> git rebase origin/master 
Successfully rebased and updated refs/heads/parse_coord.
2758 pastvu:parse_coord> git push
```

2023-01-28 11:21 UTC, kabalin requested changes
Оставил еще один комментарий, вроде бы других замечаний нет. Спасибо! (сейчас вам просто заново checkout ветки нужно сделать и добавить коммит, затем push)

2023-01-28 11:21 UTC, kabalin commented on public/js/lib/Utils.js
> +                    coordsString = coordsString.replace(/градусов/g, 'г').replace('%2C', ', ');
Можно было бы `const deg_pat = /Г(Р)?(АД)?(УСОВ)?/ig;` покрыть вариант с градусами. C html encoding всю строку нужно декодировать наверное, там же могут пробелы и в других местах быть, не только между координатами, либо совсем убрать.

2023-01-28 12:02 UTC, yuriy-zhilovets2 commented on public/js/lib/Utils.js
> +                    coordsString = coordsString.replace(/градусов/g, 'г').replace('%2C', ', ');
> Можно было бы const deg_pat = /Г(Р)?(АД)?(УСОВ)?/ig; покрыть вариант с градусами.
Этот вариант покрыт в коде, в РВ это сделать нельзя опять-таки из-за буквы С.

2023-01-28 12:03 UTC, yuriy-zhilovets2 commented on public/js/lib/Utils.js
> +                    coordsString = coordsString.replace(/градусов/g, 'г').replace('%2C', ', ');
В Гитхабе можно объединять коммиты в pull request. У вас это выключено? Что-то не могу найти.

2023-01-28 12:36 UTC, kabalin commented on public/js/lib/Utils.js
> +                    coordsString = coordsString.replace(/градусов/g, 'г').replace('%2C', ', ');
> > Можно было бы const deg_pat = /Г(Р)?(АД)?(УСОВ)?/ig; покрыть вариант с градусами.
> 
> Этот вариант покрыт в коде, в РВ это сделать нельзя опять-таки из-за буквы С.

А sec_pat такой проблемы не имеет?

> В Гитхабе можно объединять коммиты в pull request. У вас это выключено? Что-то не могу найти.

Это при мерже PR возможно.

2023-01-28 12:49 UTC, yuriy-zhilovets2 commented on public/js/lib/Utils.js
> +                    coordsString = coordsString.replace(/градусов/g, 'г').replace('%2C', ', ');
А дальше как в анекдоте про чайник - с этим разбирается уже сама библиотека. Автор вводит там второй РВ довольно мутного содержания - специально под этот случай.
У меня уже была мысль плюнуть на эту библиотеку и сделать что-то на pegjs, но я как подумаю, сколько там вариантов, да еще неоднозначных...

2023-01-31 10:03 UTC, kabalin commented
c `sec_pat` тоже проблема с заменой буквы C не там где требуется: строка ` '45 градусов 11 минут 45 секунд с. ш. 33°22′38″ в. д.'` превращается в `45 D 11 M 45 Nекунд S. ш. 33°22′38″ E` - вы сами то тестировали этот код? Короче говоря я изменяю эту часть кода и оставляю только совместимость с координатами википедии, все остальное, если потребуется, можно добавить либо через библиотеку (там есть тесты кстати) либо сюда, но так чтобы это работало.

Вы похоже pull и затем force push снова сделали, опять коммитов стало 17 штук, я это все сквошу в один коммит и добавляю свои изменения сверху отдельным коммитом.

2023-01-31 10:28 UTC, merged