Bugfix/restore ability to moderate disallowed comments
PastVu/pastvu pull request #575
Opened 2023-02-17 01:27 UTC by circus2271

for user with moderator rights:
![localhost_3000_p_4 (2)](https://user-images.githubusercontent.com/6430448/219524243-9656b422-5e0e-4d70-b98f-d8318e2336cd.png)
![localhost_3000_p_4 (3)](https://user-images.githubusercontent.com/6430448/219524252-ebcc049f-15fa-4d7a-9ba0-3ec4983288f3.png)
then after page refresh
![localhost_3000_p_4 (4)](https://user-images.githubusercontent.com/6430448/219524260-60002336-895b-4a1d-92e5-507a152eba23.png)

for regular user:
![localhost_3000_p_4 (8)](https://user-images.githubusercontent.com/6430448/219525713-182e51ac-c0f0-4f1f-a3cc-466f12c8c44a.png)
![localhost_3000_p_4 (9)](https://user-images.githubusercontent.com/6430448/219525719-9a3e3b54-b0a3-432d-8393-1c6569bca787.png)

Resolves #137

2023-02-18 00:05 UTC, kabalin requested changes
Hi @circus2271, thanks a lot for contributing! Some changes are needed, see the comments. Also please mention the bug issue id in the commit message body and ideally squash commits into one.

2023-02-18 00:05 UTC, kabalin commented on views/module/comment/cdotauth.pug
> +        | {{??it.mod}}
I suggest not to duplicate same actions in a different control statement, but rather refactor existing content of `.cacts` cotnainer:
1. Remove condition at line 29 and wrap "reply" action in it, as 
```
{{?it.reply}}
span.cact.reply Ответить
{{?}}
2. Rewrite conditions for "edit" and "delete" actions as `{{?it.mod || (it.reply && c.can.edit)}}`

After above changes you you will likely have a leading dot delimiter in admin/moderator view when commenting is disabled, just hide it using css (hint: we never use `.dotDelimeter` as first child).

2023-02-19 11:04 UTC, kabalin approved these changes

2023-02-19 11:05 UTC, merged

2023-02-19 11:08 UTC, kabalin commented
Thanks Pavel, congratulations on your first PR being merged to PastVu! 🥳

2023-02-19 14:04 UTC, circus2271 commented
Thanks

2023-02-19 23:34 UTC, kabalin commented
`en` branch automerge confict is resolved at 544139864a81ec2acdbb87ea8a794fb0140b9009