Show other markers on the map in the edit mode
PastVu/pastvu pull request #581
Opened 2023-03-02 13:50 UTC by circus2271

Resolves #482
![localhost_3000_p_5 (16)](https://user-images.githubusercontent.com/6430448/222444777-2d9105df-90aa-4d17-a294-a86d7de7e7e3.png)
![localhost_3000_p_5 (17)](https://user-images.githubusercontent.com/6430448/222444792-9cd8e796-42c2-47b7-ac0e-f05531d09109.png)
<img src="https://user-images.githubusercontent.com/6430448/222444790-7a2640f5-741a-4eb1-a944-e3c55e569976.png"  width="50%"/> 
<img src="https://user-images.githubusercontent.com/6430448/222444788-ace3021b-d23e-4539-adac-b1c4c98252c6.png" width="50%"/>

2023-03-02 14:45 UTC, kabalin commented
Thanks @circus2271, this needs to be improved:
1. When I edit existing point and move pin to the different location, the original point remains in place:
![image](https://user-images.githubusercontent.com/329780/222458951-da358722-3cec-46d6-a7dc-1cac303dc40c.png)
The current point needs to be excluded from the list of markers.
2. Other displayed points are clickable, it makes very easy to navigate away from editing more by accidental click on any other point, not sure how critical it is, but I think it is better not to process other point click event while photo is in editing more (pinging @paul-k-pastvu for opinion).

2023-03-04 10:55 UTC, circus2271 commented
oh, there is no need to calculate highlighted photo via its geolocation, as it is available via `pointMarkerHL`

2023-03-07 13:13 UTC, kabalin requested changes
Thanks for your work @circus2271, see the comments.

2023-03-07 13:13 UTC, kabalin commented on public/js/module/map/map.js
> +                    this.markerManager.layerPhotos.removeLayer(highlightedPhotoLayer);
This does not quite work, if you move editing pin out of screen by dragging the map and then drag it back, the point will be re-added, also this is not ideal to loop over all points every time we editing to find the right point (as pointed earlier). I suggest to refactor this in a way that `cid` would be used to identify the point. To do this:
1. Keep `cid` of editing point in map controller object.
2. When editing mode is on, identify current point using `photos[cid].marker` (markers module) and remove it from layer group (`this.markerManager.layerPhotos.removeLayer`).
3. When new markers are added as result of panning/zooming map and editing is on, check if newly added point is matching editing `cid`, if so, do not add it to the layer group.
4. When editing mode is off, add a new point marker only to the layer group, no need to refresh all.

2023-03-07 16:13 UTC, circus2271 commented on public/js/module/map/map.js
> +                    this.markerManager.layerPhotos.removeLayer(highlightedPhotoLayer);
ok, I'll see

2023-03-12 23:18 UTC, kabalin commented
@circus2271 а у вас аккаунт на PastVu есть? Хочу упомянуть в истории изменений если не возражаете (готовим новость).

2023-03-13 09:39 UTC, circus2271 commented
> @circus2271 а у вас аккаунт на PastVu есть? Хочу упомянуть в истории изменений если не возражаете (готовим новость).

привет

да, есть ([set_me_free](https://pastvu.com/u/set_me_free/))
конечно, не возражаю, спасибо

2023-03-19 22:40 UTC, circus2271 commented on public/js/module/map/map.js
> +                    this.markerManager.layerPhotos.removeLayer(highlightedPhotoLayer);
(пока что отдыхаю)

2023-09-26 11:56 UTC, kabalin commented on public/js/module/map/map.js
> +                    this.markerManager.layerPhotos.removeLayer(highlightedPhotoLayer);
Hey @circus2271, are you planning to complete this at any time soon? If not I can take it over and finish (if you don't mind).

2023-09-26 12:19 UTC, circus2271 commented on public/js/module/map/map.js
> +                    this.markerManager.layerPhotos.removeLayer(highlightedPhotoLayer);
No, I don't mind at all
That would be great, thanks

(I was to lazy to complete this)

2026-08-03 05:45 UTC, aeifn commented
Closing as stale.

2026-08-03 05:45 UTC, closed without merging